[meta]
name = "stokes_wave"
description = "Stokes I wave simulation based on ESI tutorial."
version = "v2406"

[flags]
[flags.features]
six_dof = false
forces = false
probes = false
meshing = false
waves = true

[parameters]
endTime = 5.0
maxCo = 1.0
maxAlphaCo = 1.0
writeInterval = 0.05
mass = 1.0
CoM = "(0 0 0)"
MoI = "(1 1 1)"
