[meta]
name = "kcs_hull"
description = "KRISO Container Ship (KCS) resistance test."
version = "of13"

[flags]
[flags.features]
six_dof = false
forces = true
probes = true

[parameters]
endTime = 20.0
# KCS Length ~ 230m, but usually scaled. Assuming model scale L=7.2786m (typical)
velocity = 2.196 # Froude 0.26
maxCo = 0.8
writeInterval = 0.5
mass = 320.0 # Model scale mass
CoM = "(0 0 0)"
MoI = "(200 1000 200)"
scale = 0.0227
length = 7.27
