[meta]
name = "series60"
# base_tutorial removed, using templates/base + features


description = "Series 60 (Cb=0.60) benchmark hull."
version = "of13"

[flags]
[flags.features]
six_dof = false
forces = true
probes = false

[parameters]
endTime = 10.0 # (Base: 5.0)
velocity = 1.0 # (Base: 1.668)
maxCo = 1.0 # (Base: Undefined/Fixed)
writeInterval = 0.25
mass = 80.0 # (Base: N/A)
CoM = "(0 0 0)"
MoI = "(10 80 10)"
scale = 0.00192
length = 2.4
