[meta]
name = "dtc_test"
version = "of2406"
geometry_name = "dtc_hull_esi"

[flags]
[flags.features]
meshing = true
six_dof = false
waves = false

[parameters]
scale = 1.0
velocity = 1.668
froude = 0.218
draft = 0.2
